[package]
name = "steppe"
version = "0.1.0"
edition = "2024"

[dependencies]
convert_case = "0.8.0"
enum-iterator = "2.1.0"
indexmap = "2.10.0"
serde = { version = "1.0.219", features = ["derive"] }
utoipa = "5.4.0"

[dev-dependencies]
insta = { version = "1.43.1", features = ["json"] }
serde_json = "1.0.140"
